site_name: sgmusic
repo_url: https://github.com/sg60/sgmusic
repo_name: sg60/sgmusic
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  font:
    text: Fira Sans
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

markdown_extensions:
  # Python Markdown
  - meta
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      watch:
        - sgmusic

extra_css:
  - stylesheets/extra.css
