# This workflow will upload a Python Package using Poetry when a release is created

name: Upload Python Package

on:
  # release:
  #   types: [released]
  workflow_dispatch:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: SG60/setup-poetry@v1

      - name: Build package for distribution
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
