# This workflow will create a release when a semver tag is created

name: Release

on:
  # push:
  #   tags:
  #     - "v*.*.*"
  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    uses: ./.github/workflows/code-style.yml
    
  python-publish:
    uses: ./.github/workflows/python-publish.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    needs: [test, lint]
 
  documentation:
    needs: python-publish
    # needs: release
    uses: ./.github/workflows/documentation.yml
