# This workflow will create a release when a semver tag is created

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  lint:
    uses: ./.github/workflows/code-style.yml

  release:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: yes

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Update and deploy new documentation
        run: |
          poetry install
          poetry run pip install mkdocs-material mkdocstrings
          poetry run mkdocs gh-deploy --force
